### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xmusblack** [eslam3kl/3klCon#4]
Traceback (most recent call last):
  File "3klcon.py", line 95, in <module>
    dir_check = input("[+] Perfrom directory brute forcing at all subdomains?\n[*] If [yes] it will take long time [yes/no] ")
  File "<string>", line 1, in <module>
NameError: name 'no' is not defined

**Comment by eslam3kl** [comment]
Hi, Thanks for using my tool 
Just check that you use python3 not python2
